spring:
  datasource:
    url: jdbc:h2:mem:testormdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true


logging:
  level:
    ROOT: ERROR