create table avatars (
                         id bigint generated by default as identity,
                         photo_url varchar(255),
                         primary key (id)
);

create table courses (
                         id bigint generated by default as identity,
                         course_name varchar(255),
                         primary key (id)
);

create table emails (
                        id bigint generated by default as identity,
                        email varchar(255),
                        student_id bigint,
                        primary key (id)
);

create table student_courses (
                                 student_id bigint not null,
                                 course_id bigint not null
);

create table students (
                          id bigint generated by default as identity,
                          student_name varchar(255) not null,
                          avatar_id bigint,
                          primary key (id)
);