condition:
  alexey-exists: true
  yanis-exists: true

spring:
  profiles:
    #Доступные профили: Oleg и Peter
    active: Peter, Oleg

logging:
  level:
    root: ERROR


---
spring:
  profiles: Peter
